---
- hosts: all
#  become: true

  tasks:
  - name: create a docker image with deployed waf file
    command: docker build -t yeavov/cicd-project-ansible .
    args:
       chdir: /root

  - name: push the image on Docker Hub
    command: docker push yeavov/cicd-project-ansible

  - name: remove the docker image from the ansible server
    command: docker rmi yeavov/cicd-project-ansible
    ignore_errors: yes
