---
- hosts: all
# become: true

  tasks:
  - name: stop current running container
    command: docker stop my_cicd_project
    ignore_errors: yes
  
  - name: remove stopped container
    command: docker rm my_cicd_project
    ignore_errors: yes
  
  - name: remove current docker image
    command: docker rmi yeavov/cicd-project-ansible
    ignore_errors: yes

  - name: pull the newest docker image from Docker hub
    command: docker pull yeavov/cicd-project-ansible

  - name: create a container using cicd-project-ansible
    command: docker run -d --name my_cicd_project -p 8080:8080 yeavov/cicd-project-ansible
