---
- name: Create pods using deployment
  hosts: kubernetes
  # become: true
  # user: ubuntu

  tasks:
  - name: create a deployment
    command: minikube kubectl -- apply -f cicd-devops-deployment.yml