---
- name: Create pods using deployment
  hosts: kubernetes
  # become: true
  # user: ubuntu

  tasks:
  - name: create a deployment
    command: /usr/local/bin/minikube kubectl -- apply -f /root/cicd-devops-deployment.yml
